[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "migration"
path = "src/main.rs"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration = { version = "0.12", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
async-std = { version = "1", features = ["attributes", "tokio1"] }
