//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude ;

pub mod planet ;
pub mod user ;
pub mod combat_log;
pub mod fleet_mission ;
pub mod transport_log ;
pub mod message ;
pub mod construction_queue;
pub mod conversation;
pub mod market_listing;
pub mod market_transaction;
pub mod server_resource_stats;
pub mod market_price_history;
pub mod server_config;
pub mod resource_slot;
pub mod announcement;

// Alliance system
pub mod alliance;
pub mod alliance_member;
pub mod alliance_invitation;

// Missions & Achievements system
pub mod daily_mission;
pub mod user_daily_mission;
pub mod achievement;
pub mod user_achievement;
pub mod login_streak;

// Officers system
pub mod officer_template;
pub mod user_officer;

// Sabotage system
pub mod sabotage_effect;
pub mod casus_belli;

// Tech Tree system (Expansion 2.0)
pub mod technology;
pub mod technology_requirement;
pub mod planet_technology;
pub mod ship_type;
pub mod ship_requirement;
pub mod planet_ship;
pub mod rapid_fire_rule;
pub mod building_type;
pub mod building_requirement;
pub mod planet_building;
pub mod defense_type;
pub mod defense_requirement;
pub mod planet_defense;

// Global chat system
pub mod global_chat_message;

// Social system
pub mod friendship;

// Fleet presets
pub mod fleet_preset;

// Bounty board
pub mod bounty;

// Flagship system
pub mod flagship;
pub mod flagship_module_type;
pub mod flagship_module;

// Auth system
pub mod password_reset_token;