//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super :: planet :: Entity as Planet ;
pub use super :: user :: Entity as User ;
pub use super :: fleet_mission :: Entity as FleetMission ;
pub use super :: combat_log :: Entity as CombatLog ;
pub use super :: transport_log :: Entity as TransportLog ;
pub use super :: message :: Entity as Message ;
pub use super :: construction_queue :: Entity as ConstructionQueue ;
pub use super :: conversation :: Entity as Conversation ;
pub use super :: market_listing :: Entity as MarketListing ;
pub use super :: market_transaction :: Entity as MarketTransaction ;
pub use super :: server_resource_stats :: Entity as ServerResourceStats ;
pub use super :: market_price_history :: Entity as MarketPriceHistory ;
pub use super :: server_config :: Entity as ServerConfig ;
pub use super :: resource_slot :: Entity as ResourceSlot ;
pub use super :: announcement :: Entity as Announcement ;

// Alliance system
pub use super :: alliance :: Entity as Alliance ;
pub use super :: alliance_member :: Entity as AllianceMember ;
pub use super :: alliance_invitation :: Entity as AllianceInvitation ;

// Missions & Achievements system
pub use super :: daily_mission :: Entity as DailyMission ;
pub use super :: user_daily_mission :: Entity as UserDailyMission ;
pub use super :: achievement :: Entity as Achievement ;
pub use super :: user_achievement :: Entity as UserAchievement ;
pub use super :: login_streak :: Entity as LoginStreak ;

// Officers system
pub use super :: officer_template :: Entity as OfficerTemplate ;
pub use super :: user_officer :: Entity as UserOfficer ;

// Sabotage system
pub use super :: sabotage_effect :: Entity as SabotageEffect ;
pub use super :: casus_belli :: Entity as CasusBelli ;

// Tech Tree system (Expansion 2.0)
pub use super :: technology :: Entity as Technology ;
pub use super :: technology_requirement :: Entity as TechnologyRequirement ;
pub use super :: planet_technology :: Entity as PlanetTechnology ;
pub use super :: ship_type :: Entity as ShipType ;
pub use super :: ship_requirement :: Entity as ShipRequirement ;
pub use super :: ship_building_requirement :: Entity as ShipBuildingRequirement ;
pub use super :: planet_ship :: Entity as PlanetShip ;
pub use super :: rapid_fire_rule :: Entity as RapidFireRule ;
pub use super :: building_type :: Entity as BuildingType ;
pub use super :: building_requirement :: Entity as BuildingRequirement ;
pub use super :: planet_building :: Entity as PlanetBuilding ;
pub use super :: defense_type :: Entity as DefenseType ;
pub use super :: defense_requirement :: Entity as DefenseRequirement ;
pub use super :: planet_defense :: Entity as PlanetDefense ;

// Global chat system
pub use super :: global_chat_message :: Entity as GlobalChatMessage ;

// Social system
pub use super :: friendship :: Entity as Friendship ;

// Fleet presets
pub use super :: fleet_preset :: Entity as FleetPreset ;

// Bounty board
pub use super :: bounty :: Entity as Bounty ;

// Flagship system
pub use super :: flagship :: Entity as Flagship ;
pub use super :: flagship_module_type :: Entity as FlagshipModuleType ;
pub use super :: flagship_module :: Entity as FlagshipModule ;

// Auth system
pub use super :: password_reset_token :: Entity as PasswordResetToken ;

// Black market system
pub use super :: black_market_item :: Entity as BlackMarketItem ;
pub use super :: user_inventory :: Entity as UserInventory ;
pub use super :: pirate_extortion :: Entity as PirateExtortion ;

// Economy log
pub use super :: economy_log :: Entity as EconomyLog ;

// Notification system
pub use super :: notification :: Entity as Notification ;

// Debris fields (Expansion 5.0)
pub use super :: debris_field :: Entity as DebrisField ;
// Zone Aérienne de Combat (ZAC)
pub use super :: planet_combat_zone :: Entity as PlanetCombatZone ;
// PVE Events system
pub use super :: server_event_type :: Entity as ServerEventType ;
pub use super :: server_event :: Entity as ServerEvent ;
pub use super :: server_event_participation :: Entity as ServerEventParticipation ;
pub use super :: server_event_action :: Entity as ServerEventAction ;
