//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19



use sea_orm :: entity :: prelude :: * ; use serde :: Serialize ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize)] # [sea_orm (table_name = "user")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , # [sea_orm (unique)] pub username : String , pub password_hash : String , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }